/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_24 (
    input [5:0] alu_fn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] boole
  );
  
  
  
  always @* begin
    boole = 16'h0000;
    
    case (alu_fn)
      6'h10: begin
        boole = 16'h0000;
      end
      6'h11: begin
        boole = a & b;
      end
      6'h12: begin
        boole = a & ~b;
      end
      6'h13: begin
        boole = a;
      end
      6'h14: begin
        boole = ~a & b;
      end
      6'h15: begin
        boole = b;
      end
      6'h16: begin
        boole = a ^ b;
      end
      6'h17: begin
        boole = a | b;
      end
      6'h18: begin
        boole = ~(a | b);
      end
      6'h19: begin
        boole = ~(a ^ b);
      end
      6'h1a: begin
        boole = ~b;
      end
      6'h1b: begin
        boole = ~(~a & b);
      end
      6'h1c: begin
        boole = ~a;
      end
      6'h1d: begin
        boole = ~(a & ~b);
      end
      6'h1e: begin
        boole = ~(a & b);
      end
      6'h1f: begin
        boole = 16'h0001;
      end
      default: begin
        boole = 16'h0000;
      end
    endcase
  end
endmodule
