/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_12 (
    input [4:0] char,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 7'h00;
      end
      1'h1: begin
        segs = 7'h5f;
      end
      2'h2: begin
        segs = 7'h7c;
      end
      2'h3: begin
        segs = 7'h39;
      end
      3'h4: begin
        segs = 7'h5e;
      end
      3'h5: begin
        segs = 7'h79;
      end
      3'h6: begin
        segs = 7'h71;
      end
      3'h7: begin
        segs = 7'h3d;
      end
      4'h8: begin
        segs = 7'h74;
      end
      4'h9: begin
        segs = 7'h30;
      end
      4'ha: begin
        segs = 7'h1e;
      end
      4'hb: begin
        segs = 7'h70;
      end
      4'hc: begin
        segs = 7'h38;
      end
      4'hd: begin
        segs = 7'h77;
      end
      4'he: begin
        segs = 7'h54;
      end
      4'hf: begin
        segs = 7'h5c;
      end
      5'h10: begin
        segs = 7'h73;
      end
      5'h11: begin
        segs = 7'h67;
      end
      5'h12: begin
        segs = 7'h31;
      end
      5'h13: begin
        segs = 7'h6d;
      end
      5'h14: begin
        segs = 7'h78;
      end
      5'h15: begin
        segs = 7'h1c;
      end
      5'h16: begin
        segs = 7'h3e;
      end
      5'h17: begin
        segs = 7'h7e;
      end
      5'h18: begin
        segs = 7'h76;
      end
      5'h19: begin
        segs = 7'h6e;
      end
      5'h1a: begin
        segs = 7'h5b;
      end
      5'h1b: begin
        segs = 7'h4f;
      end
      default: begin
        segs = 7'h77;
      end
    endcase
  end
endmodule
