/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    input usb_rx,
    output reg usb_tx,
    output reg [7:0] custom_seg,
    output reg [4:0] custom_sel,
    output reg [0:0] input_sel,
    output reg [7:0] input_seg,
    output reg [2:0] led_lives,
    input [0:0] increase_button,
    input [0:0] decrease_button,
    input [0:0] start_button,
    input [0:0] enter_button,
    input [0:0] reset_button,
    input [0:0] onoff_button
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_enter_btn_out;
  reg [1-1:0] M_enter_btn_in;
  button_conditioner_1 enter_btn (
    .clk(clk),
    .in(M_enter_btn_in),
    .out(M_enter_btn_out)
  );
  wire [1-1:0] M_start_btn_out;
  reg [1-1:0] M_start_btn_in;
  button_conditioner_1 start_btn (
    .clk(clk),
    .in(M_start_btn_in),
    .out(M_start_btn_out)
  );
  wire [1-1:0] M_reset_btn_out;
  reg [1-1:0] M_reset_btn_in;
  button_conditioner_1 reset_btn (
    .clk(clk),
    .in(M_reset_btn_in),
    .out(M_reset_btn_out)
  );
  wire [1-1:0] M_onoff_btn_out;
  reg [1-1:0] M_onoff_btn_in;
  button_conditioner_1 onoff_btn (
    .clk(clk),
    .in(M_onoff_btn_in),
    .out(M_onoff_btn_out)
  );
  wire [1-1:0] M_enter_edge_out;
  reg [1-1:0] M_enter_edge_in;
  edge_detector_2 enter_edge (
    .clk(clk),
    .in(M_enter_edge_in),
    .out(M_enter_edge_out)
  );
  wire [1-1:0] M_start_edge_out;
  reg [1-1:0] M_start_edge_in;
  edge_detector_2 start_edge (
    .clk(clk),
    .in(M_start_edge_in),
    .out(M_start_edge_out)
  );
  wire [1-1:0] M_reset_edge_out;
  reg [1-1:0] M_reset_edge_in;
  edge_detector_2 reset_edge (
    .clk(clk),
    .in(M_reset_edge_in),
    .out(M_reset_edge_out)
  );
  wire [1-1:0] M_onoff_edge_out;
  reg [1-1:0] M_onoff_edge_in;
  edge_detector_3 onoff_edge (
    .clk(clk),
    .in(M_onoff_edge_in),
    .out(M_onoff_edge_out)
  );
  wire [8-1:0] M_game_custom_seg;
  wire [5-1:0] M_game_custom_sel;
  wire [1-1:0] M_game_input_sel;
  wire [8-1:0] M_game_input_seg;
  wire [3-1:0] M_game_led_lives;
  reg [1-1:0] M_game_increase_button;
  reg [1-1:0] M_game_decrease_button;
  reg [1-1:0] M_game_start_switch;
  reg [1-1:0] M_game_enter_switch;
  reg [1-1:0] M_game_reset_switch;
  reg [1-1:0] M_game_onoff_switch;
  game_main_4 game (
    .clk(clk),
    .rst(rst),
    .increase_button(M_game_increase_button),
    .decrease_button(M_game_decrease_button),
    .start_switch(M_game_start_switch),
    .enter_switch(M_game_enter_switch),
    .reset_switch(M_game_reset_switch),
    .onoff_switch(M_game_onoff_switch),
    .custom_seg(M_game_custom_seg),
    .custom_sel(M_game_custom_sel),
    .input_sel(M_game_input_sel),
    .input_seg(M_game_input_seg),
    .led_lives(M_game_led_lives)
  );
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_5 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    M_start_btn_in = start_button;
    M_start_edge_in = M_start_btn_out;
    M_game_start_switch = M_start_edge_out;
    M_enter_btn_in = enter_button;
    M_enter_edge_in = M_enter_btn_out;
    M_game_enter_switch = M_enter_edge_out;
    M_reset_btn_in = reset_button;
    M_reset_edge_in = M_reset_btn_out;
    M_game_reset_switch = M_reset_edge_out;
    M_onoff_btn_in = onoff_button;
    M_onoff_edge_in = M_onoff_btn_out;
    M_game_onoff_switch = M_onoff_edge_out;
    M_game_increase_button = increase_button;
    M_game_decrease_button = decrease_button;
    custom_seg = M_game_custom_seg;
    custom_sel = M_game_custom_sel;
    input_sel = M_game_input_sel;
    input_seg = M_game_input_seg;
    led_lives = M_game_led_lives;
  end
endmodule
