/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module difficulty2_15 (
    input [3:0] rng,
    output reg [4:0] question0,
    output reg [4:0] question1,
    output reg [4:0] question2,
    output reg [4:0] question3,
    output reg [4:0] question4
  );
  
  
  
  always @* begin
    
    case (rng)
      default: begin
        question0 = 5'h0c;
        question1 = 5'h05;
        question2 = 5'h0d;
        question3 = 5'h15;
        question4 = 5'h12;
      end
      4'h0: begin
        question0 = 5'h0c;
        question1 = 5'h05;
        question2 = 5'h0d;
        question3 = 5'h15;
        question4 = 5'h12;
      end
      4'h1: begin
        question0 = 5'h08;
        question1 = 5'h19;
        question2 = 5'h05;
        question3 = 5'h0e;
        question4 = 5'h01;
      end
      4'h2: begin
        question0 = 5'h08;
        question1 = 5'h09;
        question2 = 5'h10;
        question3 = 5'h10;
        question4 = 5'h0f;
      end
      4'h3: begin
        question0 = 5'h10;
        question1 = 5'h12;
        question2 = 5'h01;
        question3 = 5'h17;
        question4 = 5'h0e;
      end
      4'h4: begin
        question0 = 5'h0f;
        question1 = 5'h0b;
        question2 = 5'h01;
        question3 = 5'h10;
        question4 = 5'h09;
      end
      4'h5: begin
        question0 = 5'h14;
        question1 = 5'h01;
        question2 = 5'h10;
        question3 = 5'h09;
        question4 = 5'h12;
      end
      4'h6: begin
        question0 = 5'h0c;
        question1 = 5'h0c;
        question2 = 5'h01;
        question3 = 5'h0d;
        question4 = 5'h01;
      end
      4'h7: begin
        question0 = 5'h13;
        question1 = 5'h0b;
        question2 = 5'h15;
        question3 = 5'h0e;
        question4 = 5'h0b;
      end
      4'h8: begin
        question0 = 5'h02;
        question1 = 5'h09;
        question2 = 5'h13;
        question3 = 5'h0f;
        question4 = 5'h0e;
      end
      4'h9: begin
        question0 = 5'h0c;
        question1 = 5'h05;
        question2 = 5'h05;
        question3 = 5'h03;
        question4 = 5'h08;
      end
      4'ha: begin
        question0 = 5'h13;
        question1 = 5'h11;
        question2 = 5'h15;
        question3 = 5'h09;
        question4 = 5'h04;
      end
      4'hb: begin
        question0 = 5'h07;
        question1 = 5'h05;
        question2 = 5'h03;
        question3 = 5'h0b;
        question4 = 5'h0f;
      end
      4'hc: begin
        question0 = 5'h13;
        question1 = 5'h0e;
        question2 = 5'h01;
        question3 = 5'h09;
        question4 = 5'h0c;
      end
      4'hd: begin
        question0 = 5'h03;
        question1 = 5'h12;
        question2 = 5'h01;
        question3 = 5'h0e;
        question4 = 5'h05;
      end
      4'he: begin
        question0 = 5'h13;
        question1 = 5'h17;
        question2 = 5'h09;
        question3 = 5'h0e;
        question4 = 5'h05;
      end
      4'hf: begin
        question0 = 5'h12;
        question1 = 5'h01;
        question2 = 5'h16;
        question3 = 5'h05;
        question4 = 5'h0e;
      end
    endcase
  end
endmodule
